on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]

jobs:
  parse-comment:
    runs-on: ubuntu-latest
    name: Parse Comment
    steps:
      - name: Dump GitHub event
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: Issue Refs Parser Action
        uses: FujiHaruka/issue-refs-parser-action@v1.0
        id: action
        with:
          body: ${{ github.event.comment.body || github.event.issue.body || github.event.pull_request.body }}
          self_slug: FujiHaruka/actions-test
      - name: Get The Outputs
        run: |
          echo "refs: ${{ steps.action.outputs.refs }}"
          echo "external_refs: ${{ steps.action.outputs.external_refs }}"
