on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  label-to-issues:
    runs-on: ubuntu-latest
    name: Label To Refferenced Issues
    if: github.event.pull_request.merged == true
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v2
      - name: "Set up Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Dump GitHub event
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: Parse Pull Request Body
        uses: FujiHaruka/issue-refs-parser-action@v1.1
        id: action
        with:
          body: ${{ github.event.pull_request.body }}
          self_slug: FujiHaruka/actions-test
      - name: Label
        run: node ./dist/label/index.js
        env:
          REF_ISSUES: ${{ steps.action.outputs.refs }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
